# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestVerifytext():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_verifytext(self):
    self.driver.get("https://www.copart.com/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.ID, "input-search").send_keys("porsche")
    self.driver.find_element(By.ID, "input-search").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "serverSideDataTable_filter").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".odd:nth-child(1) > td:nth-child(5) > span").text == "PORSCHE"
    element = self.driver.find_element(By.ID, "serverSideDataTable_wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "serverSideDataTable_wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "serverSideDataTable_wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "serverSideDataTable_wrapper").click()
    element = self.driver.find_element(By.ID, "serverSideDataTable_wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "serverSideDataTable_wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "serverSideDataTable_wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "serverSideDataTable_wrapper").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".results-wrap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".results-wrap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".results-wrap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".results-wrap").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".results-wrap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".results-wrap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".results-wrap")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".results-wrap").click()
  
